version: "3"

volumes:
  data:
  test_data:
services:
  clj-back:
    container_name: "clj-back"
    build:
      context: ./clj-back
      dockerfile: Dockerfile.dev
    volumes:
      - ./clj-back:/usr/src/app # I want to manage volumes manually.
      - "${HOME}/.m2:/root/.m2"
      - "${HOME}/.aws:/root/.aws"
    #depends_on:
    #  - postgres
    env_file: clj-back/.env
    environment:
      dev: "true"
      PORT: 2222
    ports:
      - "7007:7007" 
      - "2222:2222"